### PR TITLE
Revise Client as instance of DeviceControl object, one client created per device

### PR DESCRIPTION
**Pull request by mikee47**
See also updates to other libraries https://github.com/mikee47/Sming/tree/update/dial-client

### CODE REVIEW

**Comment by slaff** [comment]
@mikee47 Thanks a lot for your improvements. I have noticed also the following - if a device is present on multiple network interfaces it will report multiple times and will be controlled multiple times although it is the same device: the `USN` is the same. Which results in the same commands being executed multiple times on the same device. Is there an option to discover only unique devices? For example it would be great if `ControlPoint::beginSearch(Delegate<bool(Device&)> callback)` has a second parameter `unique = true` that makes sure that the final list with devices contains only unique devices and not 3 or 4 times the same device but accessed via different network interfaces or virtual hosts?

**Comment by mikee47** [comment]
@slaff It sounds like the `uniqueServiceNames` filter isn't working quite as expected. I think that filter should probably be in the `Search` object but I'd first need to recreate the situation you describe. Can you recommend a way to do this?

NB. Only unique objects should be returned from a search and we shouldn't care what network interface is being used.

**Comment by mikee47** [comment]
@slaff I'm considering revising the UPnP library to support multiple concurrent searches. If we wanted to locate several specific devices then at present the application would have to serialise those searches which is messy. Any thoughts?

**Comment by mikee47** [comment]
@slaff My changes don't work on real ESP8266 device... fix in progress

**Pull request merged**
